GET http://localhost:3000/api/users
###

GET http://localhost:3000/api/book
### 

GET http://localhost:3000/api/book-author
### 

POST http://localhost:3000/api/book
Content-Type: application/json

{
    "title": "Book 3",
    "year": 2020,
    "rating": 3
}
###

GET http://localhost:3000/api/author/
### 

GET http://localhost:3000/api/author/625e6a70b93cf588ce6977e6
### 

POST http://localhost:3000/api/author/
Content-Type: application/json

{
    "Name": "Wilfred book3",
    "town": "Liverpool",
    "bookId": "625e65e6b0d281db9cb103f3"
}
###